<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{2caae984-3533-4153-b882-53095de0599a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nIndex AT %Q*		:	DINT;
	sText AT %Q*		:	T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>